#pragma once

#include "cuda_utils.cuh"
#include <cstdint>

namespace flash_engine {
namespace speculative {

// Configuration for Speculative Decoding Verification
struct SpeculativeVerifyConfig {
    int batch_size;          // Batch size (B)
    int num_draft_tokens;    // Number of speculative draft tokens (K), e.g. 4, 8
    int vocab_size;          // Vocabulary size (V) e.g. 32000, 128256
    float temperature;       // Sampling temperature (0.0f = greedy argmax)
    bool use_stochastic;     // True = Rejection sampling with probabilities, False = Greedy exact match

    SpeculativeVerifyConfig(int b, int k, int v, float temp = 0.0f, bool stochastic = false)
        : batch_size(b), num_draft_tokens(k), vocab_size(v),
          temperature(temp), use_stochastic(stochastic) {}
};

// Host dispatch for Parallel Speculative Verification Kernel
// Evaluates candidate tokens across all draft positions in parallel,
// verifies sequential acceptance, samples the recovery token upon rejection,
// and outputs the accepted tokens and counts in a single fused kernel pass.
cudaError_t launch_speculative_verification(
    const float* d_target_logits,        // [B, K + 1, V] target model candidate logits
    const int64_t* d_draft_tokens,       // [B, K] speculative tokens generated by draft model
    const float* d_draft_probs,          // [B, K] probabilities assigned by draft model (optional)
    const float* d_rand_uniform,         // [B, K] uniform random values for rejection sampling (optional)
    int64_t* d_accepted_tokens,          // [B, K + 1] verified and accepted token sequence
    int* d_accepted_counts,              // [B] number of accepted tokens for each sequence in batch
    const SpeculativeVerifyConfig& config,
    cudaStream_t stream = nullptr
);

} // namespace speculative
} // namespace flash_engine
